### ISSUE TITLE
How to pass the postgres user and password ? 

### ISSUE THREAD

**Issue by aditya-kukde** [kprestel/pytest-docker-db#12]
I want the postgres database created with a user and password. How would I do that without a custom docker image ?

**Comment by kprestel** [comment]
I don't think you would be able to do that without using a custom docker image. At least not currently. 

How would you want to pass the user and password?

**Comment by michaelwiles** [comment]
so how do you pass a custom docker image? I'm using a dockerfile and it's not working either

I want to send env vars to the run of the docker image - that is the way to pass the username and password

**Comment by kprestel** [comment]
From the README:

`pytest --db-dockerfile=Dockerfile --db-name=test-postgres --db-port=5432 --db-host-port=5434`

Basically pass in a custom Dockerfile with whatever you want baked into it.

**Comment by kprestel** [comment]
I think I misunderstood your initial question. I added the feature I think you were asking for, here is a snippet from the README:

`pytest --db-dockerfile=Dockerfile --db-name=test-postgres --db-port=5432 --db-host-port=5434 --db-docker-env-vars=POSTGRES_PASSWORD=FOO,POSTGRES_USER=BAR`

Let me know if this is not what you were asking for.

**Comment by michaelwiles** [comment]
Thanks.

Is there to send these cars programmatically and not via the command line. I don't want my tests being dependent on command line params.

**Comment by kprestel** [comment]
Yeah, in the `ini` file:

`db-docker-env-vars=POSTGRES_PASSWORD=FOO,POSTGRES_USER=BAR`

In the future I will integrate with `pytest-dotenv` or something of that sort.
