### ISSUE TITLE
Testing Issue

### ISSUE THREAD

**Issue by ddrouin** [kprestel/pytest-docker-db#6]
When running unit tests, a couple error out due to the tests using this mount location:
`/home/kp/vol` which doesn't exist on my computer.  I switched these to /tmp and they worked fine.

**Comment by kprestel** [comment]
Good catch. I fixed this, however when I set it to `/tmp` it changed the permissions on `/tmp` causing some problems... So I set it to `/tmp/docker/`. Thanks for the report.
